### ISSUE TITLE
Nested `show()` calls throw an error

### ISSUE THREAD

**Issue by littensy** [centau/vide#31]
Nested `show()` calls (or any component that returns a function in `show`) throw the following error:

```
bind:55: attempt to index function with 'Parent'
```

### Repro

```lua
Vide.mount(function()
	local truthy = Vide.source(true)

	return Vide.show(truthy, function()
		return Vide.show(truthy, function()
			return Vide.create("Frame")({ Size = UDim2.new(1, 0, 1, 0) })
		end)
	end)
end, target)
```

**Comment by centau** [comment]
This is effectively setting, as a child, a source returning another source - this doesn't have a defined behavior. Vide will assume the value of the outer source is an instance to be parented.

Rather than allowing this I think it would be clearer to have an intermediate GUI object that can be set as a parent.

**Comment by littensy** [comment]
> This is effectively setting, as a child, a source returning another source - this doesn't have a defined behavior.

That's a good way to put it. I'll close this issue.
